version: '3.8'
services:
  load-balancer:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api-service
      - hash-generator
    networks:
      - pastebin-network

  api-service:
    build:
      context: ./backend/ApiService
      dockerfile: Dockerfile
    expose:
      - "8080"
    depends_on:
      - hash-generator
      - db
      - minio
      - redis
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/pastebin
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_DATASOURCE_DRIVER-CLASS-NAME=org.postgresql.Driver
      - HASH_GENERATOR_URL=http://hash-generator:8080/generate-hash
      - MINIO_URL=http://minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - MINIO_BUCKET_NAME=pastebin
      - TERM=xterm-256color
      - SPRING_REDIS_HOST=redis
    tty: true
    networks:
      - pastebin-network

  hash-generator:
    build:
      context: ./backend/HashGenerator
      dockerfile: Dockerfile
    expose:
      - "8080"
    environment:
      - TERM=xterm-256color
    tty: true
    networks:
      - pastebin-network

  db:
    image: postgres:12
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pastebin
      TERM: xterm-256color
    tty: true
    networks:
      - pastebin-network

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      TERM: xterm-256color
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data
    tty: true
    networks:
      - pastebin-network

  redis:
      image: redis:alpine
      ports:
        - "6379:6379"
      networks:
        - pastebin-network

networks:
  pastebin-network:
    driver: bridge

volumes:
  minio-data: