version: '3.8'
services:
  api-gateway:
    build:
      context: ./services/ApiGateway
      dockerfile: Dockerfile
    ports:
      - "3031:8080"
    depends_on:
      - api-service
      - hash-generator
      - metrics-service
      - comment-service
    networks:
      - pastebin-network

  api-service:
    build:
      context: ./services/ApiService
      dockerfile: Dockerfile
    expose:
      - "8080"
    depends_on:
      - hash-generator
      - db
      - minio
      - redis
      - metrics-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/pastebin
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.PostgreSQLDialect
      - HASH_GENERATOR_URL=http://hash-generator:8080/generate-hash
      - MINIO_URL=http://minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - MINIO_BUCKET_NAME=pastebin
      - SPRING_REDIS_HOST=redis
      - METRICS_SERVICE_URL=http://metrics-service:8081
    networks:
      - pastebin-network

  hash-generator:
    build:
      context: ./services/HashGenerator
      dockerfile: Dockerfile
    expose:
      - "8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/pastebin
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.PostgreSQLDialect
    networks:
      - pastebin-network

  db:
    image: postgres:12
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pastebin
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - pastebin-network

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    networks:
      - pastebin-network

  redis:
    image: redis:alpine
    networks:
      - pastebin-network

  metrics-service:
    build:
      context: ./services/MetricsService
      dockerfile: Dockerfile
    expose:
      - "8081"
    networks:
      - pastebin-network

  comment-service:
    build:
      context: ./services/CommentService
      dockerfile: Dockerfile
    expose:
      - "8082"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/pastebin
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.PostgreSQLDialect
    networks:
      - pastebin-network

networks:
  pastebin-network:
    driver: bridge

volumes:
  postgres_data:
  minio_data: