global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'api-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['api-service:8080']

  - job_name: 'metrics-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['metrics-service:8081']
