management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
  metrics:
    export:
      prometheus:
        enabled: true
  endpoint:
    prometheus:
      enabled: true

spring:
  redis:
    host: redis
    port: 6379
  datasource:
    url: jdbc:postgresql://db:5432/pastebin
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

hash:
  generator:
    url: http://hash-generator:8080

metrics:
  service:
    url: http://metrics-service:8081

minio:
  url: http://minio:9000
  access-key: minioadmin
  secret-key: minioadmin
  bucket-name: pastebin

server:
  servlet:
    context-path: /paste