spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:3001"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
      routes:
        - id: api-service
          uri: http://api-service:8080
          predicates:
            - Path=/api/v1/paste/**
        - id: comment-service
          uri: http://comment-service:8082
          predicates:
            - Path=/api/v1/comments/**
        - id: hash-generator
          uri: http://hash-generator:8080
          predicates:
            - Path=/hash/**
          filters:
            - RewritePath=/hash/(?<segment>.*), /$\{segment}
        - id: metrics-service
          uri: http://metrics-service:8081
          predicates:
            - Path=/api/v1/metrics/**

server:
  port: 8080

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty: DEBUG