management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
  metrics:
    export:
      prometheus:
        enabled: true
  endpoint:
    prometheus:
      enabled: true

spring:
  redis:
    host: redis
    port: 6379
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true

hash:
  generator:
    url: http://hash-generator:8080

metrics:
  service:
    url: http://metrics-service:8081

minio:
  url: http://minio:9000
  access-key: minioadmin
  secret-key: minioadmin
  bucket-name: pastebin

server:
  servlet:
    context-path: /paste