name: Java CI with Maven and Docker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        docker-compose --version

    - name: Build with Maven
      run: mvn clean package -DskipTests

    - name: Build Docker images
      run: docker-compose build

    - name: Run services
      run: docker-compose up -d

    - name: Wait for services to be ready
      run: sleep 30

    - name: Run tests for ApiService
      run: docker-compose exec -T api-service mvn test || true

    - name: Run tests for HashGenerator
      run: docker-compose exec -T hash-generator mvn test || true

    - name: Run tests for CommentService
      run: docker-compose exec -T comment-service mvn test || true

    - name: Check Docker images
      run: docker images

    - name: Cleanup
      run: docker-compose down --rmi all -v --remove-orphans