name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Install docker-compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        docker-compose --version

    - name: Build Docker images
      run: docker-compose build

    - name: Run tests
      run: |
        docker-compose up -d
        docker-compose exec -T api-gateway npm test || true
        docker-compose exec -T api-service ./gradlew test || true
        docker-compose exec -T hash-generator go test ./... || true
        docker-compose exec -T metrics-service npm test || true
        docker-compose exec -T comment-service ./gradlew test || true
        docker-compose down

    - name: Check Docker images
      run: docker images

    - name: Cleanup
      run: docker-compose down --rmi all -v --remove-orphans