name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker images
      run: docker-compose build

    - name: Run tests
      run: |
        docker-compose up -d
        docker-compose exec -T api-gateway npm test
        docker-compose exec -T api-service ./gradlew test
        docker-compose exec -T hash-generator go test ./...
        docker-compose exec -T metrics-service npm test
        docker-compose exec -T comment-service ./gradlew test
        docker-compose down

    - name: Check Docker images
      run: docker images

    - name: Cleanup
      run: docker-compose down --rmi all -v --remove-orphans