name: Java CI with Docker

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker images
      run: docker-compose build

    - name: Run services
      run: docker-compose up -d

    - name: Wait for services to be ready
      run: sleep 30

    - name: Run tests for ApiService
      run: docker-compose exec -T api-service ./gradlew test || true

    - name: Run tests for HashGenerator
      run: docker-compose exec -T hash-generator ./gradlew test || true

    - name: Run tests for CommentService
      run: docker-compose exec -T comment-service ./gradlew test || true

    - name: Check Docker images
      run: docker images

    - name: Cleanup
      run: docker-compose down --rmi all -v --remove-orphans